### PR TITLE
Updating ReadGzipHeader to prevent panics and adding test cases.

### PR DESCRIPTION
**Pull request by alistair-mclean**
Hello, I am using your package in a project at work. First off, thank you for making this. But I did run into a panic with a specific APK - and have updated the `ReadGzipHeader` function to prevent a panic. 

The panic was caused by an index out of bounds.

### CODE REVIEW

**Review by martencassel — APPROVED** [review]

**Comment by martencassel** [comment]
Thanks ! 😃

**Comment by alistair-mclean** [comment]
@martencassel Thanks for merging this! Could you please make a release tag for this so I can pull these changes into my module? I currently don't have the capability to do that, otherwise I would have pushed one.

**Comment by martencassel** [comment]
Sure. Do you want "maintainer" rights to this repo ? I can give that to you aswell so you can review prs and maintain it if you like now that you are using it in your work.

**Comment by martencassel** [comment]
Fyi
This project arose as a personal project part of my work in writing a binary repo manager server that could support alpine indexing operations

**Comment by martencassel** [comment]
https://github.com/martencassel/go-apkutils/releases/tag/v1.0.0

**Pull request merged**
